### ISSUE TITLE
Is the generated session the same one been pass via the request.session property?

### ISSUE THREAD

**Issue by joulez** [ericrasmussen/pyramid_redis_sessions#57]
Hi,
In order for multiple cookie/session support direct references to request.session (RE: set_cookie, cookie_callback) will obviously fail (sessions are managed via a sessionmanager property itself attached to the request object - WIP).
Please see review changes to [compare here](https://github.com/joulez/pyramid_redis_sessions/compare/refactor.session_callback).
Currently testing and appears to be ok. Please advise if I've missed something or discuss.
Thanks.

**Comment by ericrasmussen** [comment]
Hi there -- I'm having trouble thinking of a situation where request.session and the local session variable could or would be different since existing sessions are based on the current request and session cookie (and there can only be one session cookie per pyramid_redis_sessions config, based on the cookie name/cookie domain/etc).

If you're trying to add support in your application for multiple sessions, you might consider creating multiple pyramid_redis_sessions factories (each with their own unique config) and then writing your own session factory that would dispatch to the appropriate one based on what you need. If I'm understanding you this seems like something that should live in the app and not this library.

If I've misunderstood though please let me know what your use case is, and if possible provide a small reproducible example showing how the current process is broken.
